version: '3'

services:
  broker-local:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mensageria

networks: 
    mensageria:
      driver: bridge

      #NAVEGAR ate raiz do YML e rodar
      #docker-compose up -d


